<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Directo.Networking\Directo.Networking.csproj" />
    <ProjectReference Include="..\Directo.Storage\Directo.Storage.csproj" />
  </ItemGroup>
</Project>
